### ISSUE TITLE
TypeError: connect() argument 3 must be str, not None

### ISSUE THREAD

**Issue by eliobou** [Ailothaen/linky#2]
Bonjour,

J'ai cette erreur en exécutant le code :

Traceback (most recent call last):
  File "/srv/linky/main.py", line 23, in <module>
    linky.test_db_connection(config['database']['server'], config['database']['user'], config['database']['password'], config['database']['name'])
  File "/srv/linky/linky.py", line 64, in test_db_connection
    db, cr = open_db(server, user, password, name)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/srv/linky/linky.py", line 99, in open_db
    db = MySQLdb.connect(server, user, password, name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/MySQLdb/__init__.py", line 121, in Connect
    return Connection(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/MySQLdb/connections.py", line 193, in __init__
    super().__init__(*args, **kwargs2)
TypeError: connect() argument 3 must be str, not None

Est-ce que j'ai mal renseigné le fichier de config ? Il faut mettre des "" ? Ou une update de librairie aurait changé quelque chose ? Merci

**Comment by Ailothaen** [comment]
Bonjour,

Cela me fait penser à un paramètre "name" non spécifié dans le fichier de configuration.
Normalement, la partie "database" devrait ressembler à ça :

```yaml
database:
  server: 127.0.0.1
  name: linky
  user: linky
  password: mypassword
```

Le paramètre "name" est le nom de la base de données à laquelle on se connecte.
